version: "3.9"

services:
  server:
    image: httpd:2.4
    ports:
      - 8080:80
    volumes: 
      - type: bind
        source: "../htdocs"
        target: "/usr/local/apache2/htdocs"
    environment: 
      - TZ=Asia/Tokyo
  java:
    image: mcr.microsoft.com/vscode/devcontainers/java:0-16
    ports:
      - 8001:8001
    volumes:
      - type: bind
        source: "../"
        target: "/workspace"
    tty: true
    environment: 
      - TZ=Asia/Tokyo
  tomcat:
    image: tomcat:9.0
    ports:
      - 8888:8080
    volumes:
      - type: bind
        source: "../webapps"
        target: "/usr/local/tomcat/webapps"
    environment: 
      - TZ=Asia/Tokyo