version: "3.9"

x-chap: &CHAPTER_DIRECTORY 
  "../ch04"
x-htdocs: &HTDOCS_DIR
  "../ch04/htdocs"
x-webapps: &WEBAPPS_DIR
  "../ch04/webapps"

services:
  server:
    image: httpd:2.4
    ports:
      - 8080:80
    volumes: 
      - type: bind
        source: *HTDOCS_DIR
        target: "/usr/local/apache2/htdocs"
    environment: 
      - TZ=Asia/Tokyo
  java:
    # image: mcr.microsoft.com/vscode/devcontainers/java:0-16
    build:
      context: .
      dockerfile: ./Dockerfile.java
    ports:
      - 8001:8001
    volumes:
      - type: bind
        source: "../"
        target: "/workspace"
    tty: true
    environment: 
      - TZ=Asia/Tokyo
  tomcat:
    image: tomcat:9-jdk16-corretto
    ports:
      - 8888:8080
    volumes:
      - type: bind
        source: *WEBAPPS_DIR
        target: "/usr/local/tomcat/webapps"
    environment: 
      - TZ=Asia/Tokyo